version: '2'
services:
    noon07-app:
        image: noon07
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://noon07-mysql:3306/noon07?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=noon07-elasticsearch:9300
        ports:
            - 8080:8080
    noon07-mysql:
        extends:
            file: mysql.yml
            service: noon07-mysql
    noon07-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: noon07-elasticsearch
